export const stakeAndAdvanceAbi = [
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "user", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "stakeId", type: "uint256" }],
  },
  {
    type: "function",
    name: "drawdown",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "repay",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cancel",
    stateMutability: "nonpayable",
    inputs: [{ name: "stakeId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "raiseDispute",
    stateMutability: "nonpayable",
    inputs: [{ name: "stakeId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "autoRelease",
    stateMutability: "nonpayable",
    inputs: [{ name: "stakeId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setTreasury",
    stateMutability: "nonpayable",
    inputs: [{ name: "newTreasury", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "pullCollateralForYield",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "returnCollateralFromYield",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "effectiveCreditLimit",
    stateMutability: "view",
    inputs: [{ name: "vendor", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "platformTrackRecord",
    stateMutability: "view",
    inputs: [{ name: "vendor", type: "address" }],
    outputs: [
      { name: "drawdownCount", type: "uint256" },
      { name: "repaymentCount", type: "uint256" },
      { name: "onTimeCount", type: "uint256" },
      { name: "lateCount", type: "uint256" },
      { name: "repaidAmount", type: "uint256" },
      { name: "outstandingDebt", type: "uint256" },
      { name: "debtDueAt", type: "uint64" },
    ],
  },
] as const;
